service: which-episode-to-watch-again

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  tvshow:
    handler: handler.tvShow
    events:
      - http:
          path: tv-shows
          method: get
          cors:
            origins:
              - https://watch-roulette.netlify.app/
  random:
    handler: handler.random
    events:
      - http:
          path: random/{id}
          method: get
          cors:
            origins:
              - https://watch-roulette.netlify.app/
          request:
            parameters:
              paths:
                id: true